### ISSUE TITLE
Increase SinkCost when backhaul connection is down

### ISSUE THREAD

**Issue by PFigs** [wirepas/gateway#29]
When the transport service has no IP connectivity ensure the following:

* Set a maximum queue size for the MQTT queue

* Increase the sink cost based on the queue size

* Monitor the publish time of the last message

It is a good idea to allow the configuration of the queue size (if possible on the Paho https://pypi.org/project/paho-mqtt/#publishing) and publishing time.

**Comment by PFigs** [comment]
Should we also alter the cost based on the amount of packets fwd by the transport service? 

This would allow the traffic to be split more evenly between gateways.

**Comment by GwendalRaoul** [comment]
Implementation will soon be started. Here is the plan:

**Prerequisites:**
- Implementation must be simple in order to be testable
- Sink cost mechanism is quite "slow", meaning that changing too often the sink cost will create more issues than it solves.

**Implementation:**

1. Transport service will started with a max number of packet to be buffered (0 to diable feature). Value to set will depend on the back haul connection reliability. If on cellular with frequent short disconnections, it is better to buffer data instead of increasing the cost. It will also depend on the load of network. Transport may also have a max time without being able to transfert a packet. So the connection itself is not monitored but the consequences of it is (too many queued packet or too much time in the queue)
2. Once threshold is reached (max queuing time or number of queued packets), increase sinkCost to its maximum. 
3. Once the previously buffered packets are transmitted again to the backhaul, set sinkCost back to 0

Some mechanisms may be implemented to avoid sinkCost being switching too often (basically more than every 15 minutes)

**Comment by sterwen** [comment]
Hello Gwendal,

I am a concerned about having a lot of automatism in the gateway as this can be heavily customer application dependent. Either, this will need to a need to branch and hack or will require very complex parameter scheme. This is not only linked to that feature BTW, but this one can be particularly impacting.

**Comment by GwendalRaoul** [comment]
Hello Laurent,

What do you mean with automatism?
For this particular feature we want to keep the configuration parameters number as small as possible. And it is also the case for other features.
Testing for us is really important. If we have algorithms that are too complex with too much parameters it ends up in an un-testable system.

And this feature could be disabled of course if not necessary in a network (if this is what you mean by automatism).

What we try to achieve with this gateway reference code is to address most of the problems with "simple" solution, to have an easy modifiable code if needed for really particular cases.

Br,
Gwendal

**Comment by johanneslehmann** [comment]
Thanks Gwendal :).

Makes sense regarding the sink cost and good to understand.

About playing with the sink cost ourselves: I do think that this could be something we realistically want to do. For example we might have a gateway that has an invalid certificate to our cloud, in which case we wouldn't want to route to it. But the transport service may not know about it. Then if we use the API to set the sink cost the transport service may later change it back to something else, correct?

Not sure what the right way to architect is, but I feel what I describe is fairly important to avoiding a black hole at the application level.

What do you think?

**Comment by GwendalRaoul** [comment]
Hello Johannes,

Do you mean that because of wrong certificate the transport service will not be able to connect to mqtt?
If it is the case, the transport service will exit immediately. So we could have a feature to increase the sinkCost from transport in case the first connection is not working. Or it could be outside of transport service managed by the service in charge of starting Transport Service.

But it is true that the use case of a sinkService running without a transport service or any other custom transport available will generate a black hole situation.
In theory increasing the sinkCost should be managed outside of transport module, but right now it is the easiest solution. Because it may happen also that mqtt connection is not working but another transport module developed by a customer using a different mechanism to transfer packet is still operational. But it is outside of Wirepas scope.
That's why you will be able to disable the mechanism of increasing sinkCost from transport module configuration, to handle it differently with more parameters.

**Comment by johanneslehmann** [comment]
@GwendalRaoul I understand that the transport service will exit if it can't connect :) - this was about our own 'custom transport service'.

On second thought I fear that we may not be able to get as much mileage out of this feature (though I'm sure others will) as we might like, because for us the real deciding factor on whether we want to route to a given sink is whether our custom transport is operating correctly.

We'll give it some more thought on our end as well :).

**Comment by GwendalRaoul** [comment]
@johanneslehmann I understand your point. That's also why, I tried to decouple the algorithm in a dedicated thread that periodically check the queue of our transport. So if you cannot reuse code as it is at the moment, you may still reuse the code in your own transport.
If you need any help for adaptation, feel free to ask.

It may be good to extract it out of Wirepas Transport but then it will be really hard to have a generic algorithm to increase SinkCost based on multiple transports input. What should we do if our transport says that everything is fine but your transport says that it is not? (or the other way round).

**Comment by johanneslehmann** [comment]
@GwendalRaoul Right, reusing the existing code might be a good idea :).

For your last point, I agree that there is not generic decision that is always going to be right, but we might be able to introduce a voting system that decides whether to route to a sink. For example we could define the 'badness' of each transport not being healthy and sum up all the badnesses from the transports not running to get a sinkCost (which may be max). Would that work?

Understood that it's not in this version of the deliverable of course!
