### ISSUE TITLE
Setup dbus on a container

### ISSUE THREAD

**Issue by PFigs** [wirepas/gateway#33]
Package and launch dbus on a container to allow the sink and transport service to communicate over it instead of the host's bus.

**Comment by jbaptperez** [comment]
Hi Pedro, I'm Jean-Baptiste PEREZ from Dietal (TPPL V2 project).
I built my own gateway set-up using a containerized D-Bus service and I'd like to contribute to enhance your official set-up.

Following links to my images:
- [jbaptperez/wirepas-d-bus \[Docker Hub\]](https://hub.docker.com/repository/docker/jbaptperez/wirepas-d-bus): D-Bus image that shares the D-Bus Unix socket through a volume for the `wirepas` user;
- [jbaptperez/wirepas-sink-service \[Docker Hub\]](https://hub.docker.com/repository/docker/jbaptperez/wirepas-sink-service/general): Sink service image based on `wirepas/gateway:v1.3.0` one, with addition of the `wirepas` user to the `dialout` group to make it accessing the sink node entry in `/dev` without `root` permissions;
- [wirepas-gateway-compose \[GitHub\]](https://github.com/jbaptperez/wirepas-gateway-compose): A fully functional gateway set-up using the previously mentioned images and a MQTT broker (hard coded parameters).

This set-up solves various security issues I found in your solution:
- Of course it does not require the host to run a D-Bus daemon and share its Unix socket;
- There is no privileged access on any container (i.e. using `--privileged`, or sharing the whole `/dev` directory, etc.);
- Only the D-Bus container runs as `root`, but it may be enhanced using the `messagebus` account instead;

However, I'm hesitating to create a pull request in the `wirepas/gateway` repository because the following changes have to be made to integrate a proper D-Bus container usage:
- You should have your own multi-architecture`wirepas/d-bus` images to reference them from your docker-compose files;
- You should separate both sink and transport service images because they don't exactly need the same building: The sink service requires the `wirepas` user to belong to the `dialout` group, it also uses Python scripts or C binaries which are not used by the transport service etc.

Of course you could update the `wirepas/gateway` multi-architecture images by making the `wirepas` user member of to the `dialout` group (like I did with `jbaptperez/wirepas-sink-service`), but that does not follow the Docker philosophy where each service has its own dedicated image.

Please tell me where you want to go to and whether you would like my contribution.

**Comment by PFigs** [comment]
Hi Jean-Baptiste, 

Thanks a lot for your contribution, it tackles some of the issues identified in the past (see https://github.com/wirepas/gateway/issues/33). 

The --privileged would likely still be needed for the dev environment where often you might have the USB port changing its iteration or you wish to alter the port without changing the compose. 

You raise a valid point with the lack of multiple images. It would be good to separate the transport and the sink service like you say. The sink service could in fact be a simple scratch image with a very minimal footprint. I believe this would be a good path for a PR from you. 

I'll ping @GwendalRaoul as I am currently only a community participant and no longer working with Wirepas.

Cheers,

**Comment by jbaptperez** [comment]
> The --privileged would likely still be needed for the dev environment where often you might have the USB port changing its iteration or you wish to alter the port without changing the compose.

As the `/dev/ttyUSBX` does not guarantee to target the same device, one can use `/dev/serial/by-id/xxx` symbolic links as they always target the same device (sink).

Same with `/dev/serial/by-path/xxx` symbolic links which always target the same USB port.

Moreover, one can also add a `udev` rule to the host config that creates fixed `/dev` nodes like `/dev/sink0` once connected.

Therefore, in the case USB sinks are fixed and never unplugged, using `--device` with appropriated symbolic links should be enough (`stable` Docker compose files).

In the case USB sinks can be unplugged and changed (`dev` Docker compose files?), the ideal would be having a dedicated service/container which monitors the `/dev` directory, and starts/stops dedicated sink service containers for the connected USB sinks.
This can be done at least in two ways:
- Using a dedicated container which has a read-only access to the host `/dev` directory and which controls the Docker engine thanks to the Docker Unix socket and the Docker API;
- Using scripts in the host called by the `udev` daemon on USB plug-in or unplug.
 
> You raise a valid point with the lack of multiple images. It would be good to separate the transport and the sink service like you say. The sink service could in fact be a simple scratch image with a very minimal footprint. I believe this would be a good path for a PR from you.
> 
> I'll ping @GwendalRaoul as I am currently only a community participant and no longer working with Wirepas.

Splitting the image should not be really complicated even if integrating the resulting images within the `wirepas/gateway` repository does not seem so trivial.
Actually, I prefer waiting for the @GwendalRaoul feeling before venturing to this kind of work...

Thank you.

**Comment by PFigs** [comment]
Hi,

Wirepas' recommendation has been to use udev for defining symbolic links & using the wm-config (https://github.com/wirepas/wm-config) framework to deal with multiple device discovery and iteratio (at least for docker based installations). 

But yes, like you said, there are several improvements to security and container usage that should be taken into use. 

In my opinion, at the moment, the most important aspect to contribute is the dbus containerization. This makes it much simpler to deploy and drops the need of mapping the host's dbus.

In terms of the image splitting, the sink and transport service would each need their own multi-architecture registry (preferably using docker's buildx plugin).

Cheers,

**Comment by jbaptperez** [comment]
Hi Pedro,

> In my opinion, at the moment, the most important aspect to contribute is the dbus containerization.
> [...]
> In terms of the image splitting, the sink and transport service would each need their own multi-architecture registry (preferably using docker's buildx plugin).

I used `docker buildx` commands to push two architectures for the `jbaptperez/wirepas-d-bus:latest` tag on Docker Hub.

However, I disabled the Docker Hub automated build because it replaces the `latest` image with its own as a single architecture build.

I saw that using **hooks** and the `manifest-tool` command could solve this (see [this example](https://github.com/ckulka/docker-multi-arch-example/tree/master/hooks)), but this method is different from `docker buildx`...

Maybe do you have an howto with `docker buildx` for Docker Hub automated builds?

**Comment by GwendalRaoul** [comment]
Hi @jbaptperez ,

Sorry for late reply.
This topic is also discussed internally at Wirepas as we need it for another case. We should start working on it soon and your example is really good starting point.
We don't really have a timeline for that but it is getting more and more important for us too. I'll update this issue as soon as we have news about it.
Maybe we could have a call to see how we could work together on it.

Thanks,
Gwendal

**Comment by jbaptperez** [comment]
Hi @GwendalRaoul 

Thanks for your reply.

> Maybe we could have a call to see how we could work together on it.

Right now, I'm focusing on another project (really busy), but it will be a good think in the future.

Since my first posts, I created my own docker-compose set-up (based on your official sources :smiley:).

Sources and manual are available on GitHub.
Be careful, I changed the repository names as well as docker image tags since my last posts (broken links).

I also pushed on Docker Hub multi-architecture images based on this set-up but they are not up-to-date as I disabled the image auto-building.
It was necessary because Docker Hub doesn't support `docker buildx` extension (yet?).
Otherwise auto-build process removes images of other architectures (push of a single image bound to a tag).

Image links:
* [jbaptperez/wirepas-d-bus-service](https://hub.docker.com/repository/docker/jbaptperez/wirepas-d-bus-service)
* [jbaptperez/wirepas-mosquitto-service](https://hub.docker.com/repository/docker/jbaptperez/wirepas-mosquitto-service)
* [jbaptperez/wirepas-sink-service](https://hub.docker.com/repository/docker/jbaptperez/wirepas-sink-service)
* [jbaptperez/wirepas-transport-service](https://hub.docker.com/repository/docker/jbaptperez/wirepas-transport-service)

Source link:
* [Docker-compose set-up](https://github.com/jbaptperez/wirepas-gateway)

See you.
